services:
  - type: web
    name: real-estate-server
    env: node
    buildCommand: corepack enable && yarn set version 4.4.1 && yarn deploy:prepare
    startCommand: yarn deploy:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
