services:
  - type: web
    name: real-estate-server
    env: node
    nodeVersion: 20.11.1
    buildCommand: |
      npm install -g corepack
      corepack enable
      corepack prepare yarn@4.4.1 --activate
      yarn install
      yarn gen
      yarn build
    startCommand: yarn deploy:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
